<h1>Broadcasting</h1>

In [2]:
import numpy as np

In [3]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [4]:
# shape
my_3D_array.shape

(2, 7, 5)

In [5]:
# number of dimensions
my_3D_array.ndim

3

In [6]:
my_3D_array.size

70

In [7]:
my_3D_array.dtype

dtype('int32')

In [8]:
5 * my_3D_array -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [9]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))

In [10]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### Operations along axes

In [11]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [12]:
my_3D_array.shape

(2, 7, 5)

In [13]:
my_3D_array.sum()

2415

In [14]:
(69 * 70) / 2

2415.0

In [15]:
my_3D_array.sum(axis = 0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [16]:
my_3D_array.sum(axis = 1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [17]:
my_3D_array.sum(axis = 2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [19]:
my_2D_array = np.ones(35, dtype = 'int_').reshape((7, 5)) * 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [21]:
my_random_2D_array = np.random.random((7,5))

In [22]:
np.set_printoptions(precision = 4)
my_3D_array * my_random_2D_array

array([[[ 0.    ,  0.6967,  0.6073,  2.3095,  3.6294],
        [ 0.2604,  4.5169,  2.6018,  4.7882,  4.4705],
        [ 9.4187,  4.8969,  4.0557,  8.652 ,  7.1298],
        [ 6.4834,  3.1254,  0.2306, 12.0606,  0.7247],
        [15.9559,  2.9269, 19.5813,  3.5052, 12.3908],
        [ 4.7671, 24.7986, 12.9438, 22.9055, 25.5355],
        [23.3108, 22.0697, 16.1001, 31.3631, 30.1416]],

       [[ 7.0031, 25.08  , 11.2359, 29.2542, 35.3862],
        [ 2.083 , 30.8652, 15.6107, 25.7365, 21.8558],
        [42.3841, 20.478 , 15.885 , 31.946 , 24.9544],
        [21.6114,  9.9621,  0.7052, 35.5119,  2.0596],
        [43.8788,  7.805 , 50.7332,  8.8393, 30.4606],
        [11.441 , 58.1814, 29.7229, 51.5375, 56.3543],
        [50.5067, 46.9872, 33.7095, 64.627 , 61.1696]]])

In [23]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [24]:
my_3D_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [25]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]], dtype=int32)