<h2>Intrinsic NumPy array creation using NumPy's methods</h2>

In [1]:
import numpy as np

In [2]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
np.arange(8,15)

array([ 8,  9, 10, 11, 12, 13, 14])

In [4]:
np.arange(8,15)-8

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
np.arange(8,15)-8+1

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
len(np.arange(8,15))

7

In [7]:
my_range_array = np.arange(8,15)
my_range_array.size

7

In [8]:
np.arange(3,17,5)

array([ 3,  8, 13])

In [9]:
np.arange(36, step = 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [10]:
np.arange(0,36, step = 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35])